---
# RAG Configuration File

input_data: data/knowledge_base100.csv  # Path to the input data file

preprocessing:
  processed_data: processed_kb100.csv  # Name of the processed data file
  html_dir: html_content  # Name of the parent folder of folders with HTMLs
  data_dir: data  # Path to where all preprocessing results are stored
  text_chunk_overlap: 0  # Overlap between text chunks for indexing
  text_chunk_size: 512  # Size of text chunks for indexing
  lang_length: 5  # Maximum length of the language code

database:
  uri: http://localhost:19530  # Milvus server URI
  token:  # Authentication token for Milvus (if required)

  collection: techtask_kb  # Name of the Milvus collection
  text_size: 1024  # Size of text chunks for indexing
  vector_dim: 768  # Dimension of the vector embeddings

retrieval:
  ranker: weighted  # Default ranker to use for retrieval
  top_k: 5  # Default number of documents to retrieve
  nprobe: 10  # Parameter for ANN search
  rrf_k: 60  # Parameter for RRF ranker
  weights:
    - 0.05
    - 0.95

llm:
  model: gpt-4.1-2025-04-14  # Default LLM model to use
  temperature: 0.3  # Default temperature for LLM responses
  max_tokens: 2048  # Maximum tokens in the response
